### ISSUE TITLE
Green post count in the catalog

### ISSUE THREAD

**Issue by KatieFrogs** [doctorwth/interface-js#7]
Server side code should be able to accept this request from catalog and return green post count in the requested threads:
```js
// Get all threads in the catalog
var threads=[]
document.querySelectorAll(".is_catalog #threads>.thread").forEach(thread=>{
	threads.push(thread.id.replace("thread-",""))
})
// Send the request
GM.xmlHttpRequest({
	method:"post",
	headers:{
		"Content-type":"application/x-www-form-urlencoded"
	},
	url:"https://funposting.online/interface/get.php?mode=catalog",
	data:"thread="+threads.join(","),
	// "thread" field looks like this:
	// 1234,1324,1222,1314,1243,1211,1144
	onload:response=>{
		console.log(response.responseText)
	}
})
```
Example JSON output:
```js
{"1234":7,"1324":0,"1222":4,"1314":0,"1243":0,"1211":0,"1144":1}
```
With thread ID as the name and number of green posts as value

**Comment by doctorwth** [comment]
Can do.

I'll also be adding something for getting just the last interface reply to a thread for use with updating and thread watching. 

I'm considering modifying `get.php?thread=xxx` to have an optional `get.php?thread=xxx&after=yyy` where the after field represents a 4chan or interface post, and the return is a list of posts added after that one, for use with updating and to make is easier to eventually add interface posts to the front page.

I'll be busy for the rest of today and tonight, but I can probably have it done by tomorrow night.

**Comment by doctorwth** [comment]
Implemented.
